#!/usr/bin/env bash
#script that configures a new Ubuntu machine to respect above requirements
apt-get update 
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start