#!/usr/bin/env bash
#redirecting to another page
apt-get update 
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=Kob0G2hE8IY permanent;/g" /etc/nginx/sites-available/default
service nginx restart
