#!/usr/bin/env bash
#return 404
apt-get update 
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t};/g" /etc/nginx/sites-available/default
service nginx start
