#!/usr/bin/env bash
# Bash script
echo $$ > /var/run/holbertonscript.pid
trap 'echo Y U no love me?!' SIGINT
trap 'echo I hate the kill command ; rm /var/run/holbertonscript.pid ;exit' SIGTERM SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
    
done
