#!/usr/bin/env bash
# using while with if statement
counter=1
while [ $counter -le 10 ]; do
    echo "Holberton School"
    if [ $counter -eq 9 ]; then
        echo "Hi"
    fi
    ((counter++))
done
