#!/usr/bin/env bash
# using while with if statement
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((counter++))
done