#!/usr/bin/env bash
# using while with if statement
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((counter++))
done