#!/usr/bin/env bash
# clock using while
hours=0
minutes=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    while [ $minutes -le 59 ]
    do
        echo $minutes
        ((minutes++))
    done
    minutes=0
    ((hours++))
done