#!/usr/bin/env bash
# set Nginx as user

# kill nginx
pkill nginx

# permissions nginx config
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

# set port 80 in sites enabled
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

# kill apache
pkill -f apache2

sudo -u nginx service nginx start

