#!/usr/bin/env bash
#7 lines or less
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx start
